// <auto-generated />
using System;
using AdsRemedy.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdsRemedy.Migrations
{
    [DbContext(typeof(DBCreateOrder))]
    [Migration("20240317132342_createorder")]
    partial class createorder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdsRemedy.Models.CreateOrder", b =>
                {
                    b.Property<int>("CO_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CO_Id"), 1L, 1);

                    b.Property<string>("CO_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CO_Qty")
                        .HasColumnType("int");

                    b.Property<string>("CO_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CO_Id");

                    b.ToTable("CreateOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
